load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "mymath",
    srcs = ["mymath.cc"],
    hdrs = ["mymath.h"],
)

cc_library(
    name = "pet",
    hdrs = ["pet.h"],
)
